spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: postgres123
  jpa:
    show-sql: false

logging:
  level:
    com.guilda: INFO
